- name: run the testing script
  command: python "{{ role_path }}"/templates/credStuffTest.py {{ bigip_mgmt_vip_ip }} {{ username }} {{ password }}
  register: out
  delegate_to: 127.0.0.1
  run_once: true
- debug: var=out.stdout_lines