---
tables:
- name: feature__easyL4FirewallBlacklist
  columnNames:
  - CIDRRange
  rows: []
- name: feature__easyL4FirewallSourceList
  columnNames:
  - CIDRRange
  rows:
  - row:
    - 0.0.0.0/0
- name: monitor__Monitors
  columnNames:
  - Index
  - Name
  - Type
  - Options
  rows:
  - row:
    - '0'
    - "{{ monitor_name }}"
    - none
    - none
- name: pool__Members
  columnNames:
  - Index
  - IPAddress
  - Port
  - ConnectionLimit
  - Ratio
  - PriorityGroup
  - State
  - AdvOptions
  rows:
  - row:
    - '0'
    - "{{ bigip_mgmt_ip }}"
    - '443'
    - '0'
    - '1'
    - '0'
    - enabled
    - none
- name: pool__Pools
  columnNames:
  - Index
  - Name
  - Description
  - LbMethod
  - Monitor
  - AdvOptions
  rows:
  - row:
    - '0'
    - ''
    - ''
    - round-robin
    - '0'
    - none
- name: l7policy__rulesAction
  columnNames:
  - Group
  - Target
  - Parameter
  rows:
  - row:
    - default
    - asm/request/enable/policy
    - bundled:remote_asm1
- name: l7policy__rulesMatch
  columnNames:
  - Group
  - Operand
  - Negate
  - Condition
  - Value
  - CaseSensitive
  - Missing
  rows:
  - row:
    - default
    - ''
    - 'no'
    - ''
    - ''
    - 'no'
    - 'no'
- name: vs__BundledItems
  columnNames:
  - Resource
  rows:
  - row:
    - asm:{{ asm_policy_location }}
  - row:
    - irule:url={{ irule_location }}{{ irule_string }}
- name: vs__Listeners
  columnNames:
  - Listener
  - Destination
  rows: []
variables:
- name: extensions__Field1
  value: ''
  encrypted: 'no'
- name: extensions__Field2
  value: ''
  encrypted: 'no'
- name: extensions__Field3
  value: ''
  encrypted: 'no'
- name: feature__easyL4Firewall
  encrypted: 'no'
  value: auto
- name: feature__insertXForwardedFor
  encrypted: 'no'
  value: auto
- name: feature__redirectToHTTPS
  encrypted: 'no'
  value: auto
- name: feature__securityEnableHSTS
  encrypted: 'no'
  value: disabled
- name: feature__sslEasyCipher
  encrypted: 'no'
  value: disabled
- name: feature__statsHTTP
  encrypted: 'no'
  value: auto
- name: feature__statsTLS
  encrypted: 'no'
  value: auto
- name: iapp__apmDeployMode
  encrypted: 'no'
  value: preserve-bypass
- name: iapp__appStats
  encrypted: 'no'
  value: enabled
- name: iapp__asmDeployMode
  encrypted: 'no'
  value: preserve-bypass
- name: iapp__logLevel
  encrypted: 'no'
  value: '7'
- name: iapp__mode
  encrypted: 'no'
  value: auto
- name: iapp__routeDomain
  encrypted: 'no'
  value: auto
- name: iapp__strictUpdates
  encrypted: 'no'
  value: enabled
- name: l7policy__defaultASM
  encrypted: 'no'
  value: bypass
- name: l7policy__defaultL7DOS
  encrypted: 'no'
  value: bypass
- name: l7policy__strategy
  encrypted: 'no'
  value: "/Common/first-match"
- name: pool__DefaultPoolIndex
  encrypted: 'no'
  value: '0'
- name: pool__MemberDefaultPort
  value: ''
  encrypted: 'no'
- name: pool__addr
  encrypted: 'no'
  value: "{{ vs_address }}"
- name: pool__mask
  encrypted: 'no'
  value: 255.255.255.255
- name: pool__port
  encrypted: 'no'
  value: '443'
- name: vs__AdvOptions
  value: ''
  encrypted: 'no'
- name: vs__AdvPolicies
  value: ''
  encrypted: 'no'
- name: vs__AdvProfiles
  value: websecurity
  encrypted: 'no'
- name: vs__ConnectionLimit
  encrypted: 'no'
  value: '0'
- name: vs__Description
  value: ''
  encrypted: 'no'
- name: vs__IpProtocol
  encrypted: 'no'
  value: tcp
- name: vs__Irules
  value: ''
  encrypted: 'no'
- name: vs__Name
  encrypted: 'no'
  value: ''
- name: vs__OptionConnectionMirroring
  encrypted: 'no'
  value: disabled
- name: vs__OptionSourcePort
  encrypted: 'no'
  value: preserve
- name: vs__ProfileAccess
  value: ''
  encrypted: 'no'
- name: vs__ProfileAnalytics
  value: ''
  encrypted: 'no'
- name: vs__ProfileClientProtocol
  encrypted: 'no'
  value: "/Common/tcp"
- name: vs__ProfileClientSSL
  value: "{{ vs__ProfileClientSSL }}"
  encrypted: 'no'
- name: vs__ProfileClientSSLAdvOptions
  value: ''
  encrypted: 'no'
- name: vs__ProfileClientSSLCert
  value: ''
  encrypted: 'no'
- name: vs__ProfileClientSSLChain
  value: ''
  encrypted: 'no'
- name: vs__ProfileClientSSLCipherString
  encrypted: 'no'
  value: DEFAULT
- name: vs__ProfileClientSSLKey
  value: ''
  encrypted: 'no'
- name: vs__ProfileCompression
  value: ''
  encrypted: 'no'
- name: vs__ProfileConnectivity
  value: ''
  encrypted: 'no'
- name: vs__ProfileDefaultPersist
  value: ''
  encrypted: 'no'
- name: vs__ProfileFallbackPersist
  value: ''
  encrypted: 'no'
- name: vs__ProfileHTTP
  value: "/Common/http"
  encrypted: 'no'
- name: vs__ProfileOneConnect
  value: ''
  encrypted: 'no'
- name: vs__ProfilePerRequest
  value: ''
  encrypted: 'no'
- name: vs__ProfileRequestLogging
  value: ''
  encrypted: 'no'
- name: vs__ProfileSecurityDoS
  value: ''
  encrypted: 'no'
- name: vs__ProfileSecurityIPBlacklist
  encrypted: 'no'
  value: none
- name: vs__ProfileSecurityLogProfiles
  value: "{{ vs__ProfileSecurityLogProfiles }}"
  encrypted: 'no'
- name: vs__ProfileServerProtocol
  value: ''
  encrypted: 'no'
- name: vs__ProfileServerSSL
  value: "/Common/serverssl"
  encrypted: 'no'
- name: vs__RouteAdv
  encrypted: 'no'
  value: disabled
- name: vs__SNATConfig
  encrypted: 'no'
  value: automap
- name: vs__SourceAddress
  encrypted: 'no'
  value: 0.0.0.0/0
- name: vs__VirtualAddrAdvOptions
  value: ''
  encrypted: 'no'

