---
############
#Add objects
############
- include: testing/run_cred_stuff.yml
  when: state == "present"
  tags: [integration_test]

- include: bigip_iapp_service/set_fact_init.yml
  when: state == "present"
  tags: [api_vip_protect]

- include: bigip_iapp_service/set_fact_from_tag.yml
  when: state == "present"
  tags: [protection]

- include: bigip_iapp_template/appsvcs.yml
  when: state == "present"
  tags: [templates, api_vip_protect]
  

- include: bigip_iapp_service/api_vip_protect.yml
  when: state == "present"
  tags: [protection, api_vip_protect]

###############
#Remove objects
###############
- include: bigip_iapp_service/set_fact_init.yml
  when: state == "absent"
  
- include: bigip_iapp_service/api_vip_protect.yml
  when: state == "absent"

- include: bigip_iapp_template/appsvcs.yml
  when: state == "absent"
...
